name: MorettiのSSLCheck

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 21 * * *' 

jobs:
  CheckSSL:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install & Build
      run: |
        npm ci
        git clone https://github.com/ChenYFan/CheckSSL --depth=2
        npm run build
        cd CheckSSL
        chmod +x checker.sh
        ./checker.sh blog.081531.xyz npm.081531.xyz uptime.081531.xyz m.081531.xyz mm.081531.xyz music.081531.xyz dockerflare.081531.xyz fc.081531.xya openlist.081531.xyz meting.081531.xyz pansou.081531.xyz search.081531.xyz imgbed.081531.xyz gallery.081531.xyz moment.081531.xyz
        cp -rf ./output/ct.json ../public/ct.json
        echo "ssl.cyfan.top" > ../public/CNAME
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./public
